# Generated by Django 4.0.4 on 2022-04-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_pass', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='StreamPannel',
            fields=[
                ('id_number', models.FloatField(primary_key=True, serialize=False)),
                ('Stream_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'streampannel',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=35, null=True)),
                ('user_psswd', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
    ]
